/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.actordb.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ErrorCode implements org.apache.thrift.TEnum {
  NotLoggedIn(1),
  EmptyActorName(2),
  InvalidActorName(3),
  InvalidType(4),
  NotPermitted(5),
  SqlError(6),
  ConsensusTimeout(7),
  Error(100);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 1:
        return NotLoggedIn;
      case 2:
        return EmptyActorName;
      case 3:
        return InvalidActorName;
      case 4:
        return InvalidType;
      case 5:
        return NotPermitted;
      case 6:
        return SqlError;
      case 7:
        return ConsensusTimeout;
      case 100:
        return Error;
      default:
        return null;
    }
  }
}
